/**
 * WebSocket Message Types and Constants
 * Defines all possible socket events for the MathQuest 1v1 game
 */

// Client to Server Events
const CLIENT_EVENTS = {
  JOIN_QUEUE: 'JOIN_QUEUE',
  PLAYER_READY: 'PLAYER_READY',
  SUBMIT_ANSWER: 'SUBMIT_ANSWER',
  FINISHED_QUIZ: 'FINISHED_QUIZ',
  READY_FOR_NEXT_ROUND: 'READY_FOR_NEXT_ROUND',
  READY_TO_VIEW_RESULTS: 'READY_TO_VIEW_RESULTS',
  DISCONNECT: 'DISCONNECT',
  RECONNECT: 'RECONNECT'
};

// Server to Client Events
const SERVER_EVENTS = {
  MATCH_FOUND: 'MATCH_FOUND',
  PLAYER_READY: 'PLAYER_READY',
  ROUND_START: 'ROUND_START',
  ROUND_CATEGORY: 'ROUND_CATEGORY',
  TIME_WARNING: 'TIME_WARNING',
  ROUND_END: 'ROUND_END',
  ROUND_RESULT: 'ROUND_RESULT',
  SHOW_RESULTS: 'SHOW_RESULTS',
  BOTH_PLAYERS_READY_FOR_RESULTS: 'BOTH_PLAYERS_READY_FOR_RESULTS',
  OPPONENT_FINISHED: 'OPPONENT_FINISHED',
  MATCH_END: 'MATCH_END',
  ERROR: 'ERROR',
  PLAYER_DISCONNECTED: 'PLAYER_DISCONNECTED',
  PLAYER_RECONNECTED: 'PLAYER_RECONNECTED'
};

// Game Configuration
const GAME_CONFIG = {
  QUESTIONS_PER_ROUND: 6,
  TIME_PER_QUESTION: 15000, // 15 seconds
  TIME_WARNING_THRESHOLD: 5000, // 5 seconds warning
  ROUND_RESULT_DISPLAY_TIME: 5000, // 5 seconds
  ROUNDS_TO_WIN: 3, // Best 2 out of 3 (first to 3 wins)
  RECONNECTION_TIMEOUT: 30000, // 30 seconds to reconnect
  BONUS_POINTS_FASTEST: 50,
  POINTS_PER_CORRECT: 100
};

// Game States
const GAME_STATES = {
  WAITING: 'waiting',
  READY_CHECK: 'ready_check',
  PLAYING: 'playing',
  ROUND_RESULT: 'round_result',
  MATCH_END: 'match_end'
};

module.exports = {
  CLIENT_EVENTS,
  SERVER_EVENTS,
  GAME_CONFIG,
  GAME_STATES
};
